from unipaith.models.admin_audit_event import AdminAuditEvent
from unipaith.models.ai_artifacts import (
    AiTurn,
    MatchRationale,
    StudentFeatureVector,
)
from unipaith.models.ai_feedback import AiTurnFeedback
from unipaith.models.application import (
    AIPacketSummary,
    Application,
    ApplicationChecklist,
    ApplicationScore,
    ApplicationSubmission,
    EnrollmentRecord,
    HistoricalOutcome,
    IntegritySignal,
    Interview,
    InterviewScore,
    OfferLetter,
    ReviewAssignment,
    Rubric,
)
from unipaith.models.attribution import AttributionEvent
from unipaith.models.audit import AdmissionsAuditLog
from unipaith.models.base import Base
from unipaith.models.billing import StudentSubscription
from unipaith.models.confidence_outcome import ConfidenceOutcomePair
from unipaith.models.discovery import DiscoveryMessage, DiscoverySession
from unipaith.models.engagement import (
    CalendarItemState,
    Conversation,
    ConversationSession,
    CRMRecord,
    Message,
    SavedList,
    SavedListItem,
    StudentCalendar,
    StudentCompareItem,
    StudentEngagementSignal,
    StudentEssay,
    StudentResume,
)
from unipaith.models.follow import InstitutionFollow
from unipaith.models.goals import StudentGoal
from unipaith.models.identity import StudentIdentity
from unipaith.models.institution import (
    Campaign,
    CampaignAction,
    CampaignLink,
    CampaignRecipient,
    CampaignSuppression,
    CommunicationTemplate,
    DatasetMappingTemplate,
    DatasetVersion,
    EmployerFeedback,
    Event,
    EventRSVP,
    Inquiry,
    Institution,
    InstitutionDataset,
    InstitutionPost,
    IntakeRound,
    Program,
    ProgramChecklistItem,
    Promotion,
    Reviewer,
    School,
    StudentProgramReview,
    TargetSegment,
    UploadedContact,
    UploadedList,
)
from unipaith.models.knowledge import (
    AdvisorPersona,
    CrawlFrontier,
    EngineDirective,
    EngineLoopSnapshot,
    InteractionSignal,
    KnowledgeDocument,
    KnowledgeLink,
    PersonInsight,
)
from unipaith.models.matching import (
    DataSource,
    Embedding,
    InstitutionFeature,
    MatchResult,
    ModelRegistry,
    OfferComparison,
    PredictionLog,
    RawIngestedData,
    StudentFeature,
)
from unipaith.models.ml_loop import (
    ABTestAssignment,
    DriftSnapshot,
    EvaluationRun,
    FairnessReport,
    OutcomeRecord,
    TrainingRun,
)
from unipaith.models.needs import StudentNeed
from unipaith.models.peer import PeerConnection, PeerProfile, PeerReport
from unipaith.models.pipeline import (
    PipelineConfig,
    PipelineStageSnapshot,
)
from unipaith.models.settings import InstitutionTeamInvite, UserSettings
from unipaith.models.strategy import StudentStrategy
from unipaith.models.student import (
    AcademicRecord,
    Activity,
    OnboardingProgress,
    RecommendationRequest,
    StudentAccommodation,
    StudentCompetition,
    StudentCourse,
    StudentDataConsent,
    StudentDocument,
    StudentLanguage,
    StudentOnlinePresence,
    StudentPortfolioItem,
    StudentPreference,
    StudentProfile,
    StudentResearch,
    StudentScheduling,
    StudentVisaInfo,
    StudentWorkExperience,
    TestScore,
)
from unipaith.models.user import User, UserRole
from unipaith.models.workflow import (
    Notification,
    NotificationPreference,
    Touchpoint,
)
from unipaith.models.workshops import WorkshopFeedbackRun

__all__ = [
    "Base",
    "User",
    "UserRole",
    "StudentProfile",
    "AcademicRecord",
    "TestScore",
    "Activity",
    "StudentDocument",
    "StudentPreference",
    "RecommendationRequest",
    "StudentAccommodation",
    "StudentCompetition",
    "StudentCourse",
    "StudentDataConsent",
    "StudentLanguage",
    "StudentOnlinePresence",
    "StudentPortfolioItem",
    "StudentResearch",
    "StudentScheduling",
    "StudentVisaInfo",
    "StudentWorkExperience",
    "OnboardingProgress",
    # Discovery (Phase A — parallel session, merged in #111)
    "DiscoverySession",
    "DiscoveryMessage",
    # Discovery artifacts (Phase A — parallel session, merged in #113)
    "StudentGoal",
    "StudentNeed",
    "StudentIdentity",
    "StudentStrategy",
    "WorkshopFeedbackRun",
    # LLM-only artifacts (Phase A1)
    "StudentFeatureVector",
    "AiTurn",
    "MatchRationale",
    "AiTurnFeedback",
    "ConfidenceOutcomePair",
    "Institution",
    "School",
    "Program",
    "TargetSegment",
    "Campaign",
    "CampaignLink",
    "CampaignAction",
    "CampaignRecipient",
    "CampaignSuppression",
    "UploadedList",
    "UploadedContact",
    "CommunicationTemplate",
    "Event",
    "EventRSVP",
    "Inquiry",
    "Reviewer",
    "InstitutionDataset",
    "DatasetVersion",
    "DatasetMappingTemplate",
    "IntakeRound",
    "ProgramChecklistItem",
    "InstitutionPost",
    "Promotion",
    "StudentProgramReview",
    "EmployerFeedback",
    "HistoricalOutcome",
    "AIPacketSummary",
    "IntegritySignal",
    "Application",
    "ApplicationChecklist",
    "ApplicationSubmission",
    "ReviewAssignment",
    "Rubric",
    "ApplicationScore",
    "Interview",
    "InterviewScore",
    "OfferLetter",
    "EnrollmentRecord",
    "StudentEngagementSignal",
    "AttributionEvent",
    "InstitutionFollow",
    "PeerProfile",
    "PeerConnection",
    "PeerReport",
    "SavedList",
    "SavedListItem",
    "StudentCompareItem",
    "StudentCalendar",
    "CalendarItemState",
    "CRMRecord",
    "Conversation",
    "ConversationSession",
    "Message",
    "StudentResume",
    "StudentEssay",
    "MatchResult",
    "StudentFeature",
    "InstitutionFeature",
    "Embedding",
    "PredictionLog",
    "ModelRegistry",
    "DataSource",
    "RawIngestedData",
    "OfferComparison",
    "Notification",
    "NotificationPreference",
    "Touchpoint",
    # Settings (Spec 21)
    "UserSettings",
    "InstitutionTeamInvite",
    "OutcomeRecord",
    "EvaluationRun",
    "TrainingRun",
    "ABTestAssignment",
    "DriftSnapshot",
    "FairnessReport",
    "AdminAuditEvent",
    "AdmissionsAuditLog",
    "KnowledgeDocument",
    "KnowledgeLink",
    "CrawlFrontier",
    "EngineLoopSnapshot",
    "EngineDirective",
    "InteractionSignal",
    "PersonInsight",
    "AdvisorPersona",
    "PipelineStageSnapshot",
    "PipelineConfig",
    "StudentSubscription",
]
