"""Spec 42 §3.19 — canonical behavioral-prompt catalog (seed).

The ~60 prompts enumerated verbatim in ``Misc./Prompt Library.docx`` (the deepest
INPUT enumeration), each typed with intent / channel / format / limits. Seeded
idempotently on first read by ``PromptLibraryService`` (seed-if-empty) so prod
needs no separate seed job. ``prompt_key`` is the stable id responses reference;
the eight ``prompt_coach.CORE_INTERVIEW_KEYS`` must remain present here.
"""

from __future__ import annotations

# (prompt_key, title, intent_tag, channel, time_s, word_limit, format, evidence,
#  reuse) — channel ∈ interview|essay|short_answer|video; reuse ∈ core|school_specific.
_T = (
    # ── Elevator / self-intro (3 lengths) ──
    (
        "tell_me_about_yourself_30s",
        "Tell me about yourself (30 seconds)",
        "fit",
        "video",
        30,
        None,
        "freeform",
        False,
        "core",
    ),
    (
        "tell_me_about_yourself_2min",
        "Tell me about yourself (2 minutes)",
        "fit",
        "interview",
        120,
        None,
        "freeform",
        False,
        "core",
    ),
    (
        "tell_me_about_yourself_5min",
        "Tell me about yourself (5 minutes)",
        "fit",
        "interview",
        300,
        None,
        "freeform",
        False,
        "core",
    ),
    # ── Core behavioral stories (STAR) ──
    (
        "proudest_accomplishment",
        "Your proudest accomplishment",
        "impact",
        "interview",
        180,
        None,
        "STAR",
        True,
        "core",
    ),
    (
        "biggest_failure",
        "Your biggest failure or setback",
        "failure",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "conflict_with_teammate",
        "A conflict with a teammate",
        "conflict",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "conflict_with_authority",
        "A conflict with someone in authority",
        "conflict",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "received_critical_feedback",
        "Receiving critical feedback",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "gave_difficult_feedback",
        "Giving difficult feedback",
        "leadership",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "leadership_without_title",
        "Leading without authority",
        "leadership",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "initiative_ownership",
        "Taking initiative and ownership",
        "leadership",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "ambiguity",
        "Working through ambiguity",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "changed_your_mind",
        "Changing your mind with new evidence",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "ethical_dilemma",
        "An ethical dilemma or integrity decision",
        "ethics",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "mistake_detection_correction",
        "Detecting and correcting a mistake",
        "failure",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "pressure_deadline",
        "Managing pressure and deadlines",
        "impact",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "long_term_grit",
        "Long-term commitment and grit",
        "motivation",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "mentorship_service",
        "Helping others, mentorship, or service",
        "service",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "cross_cultural_teamwork",
        "Cross-cultural teamwork",
        "teamwork",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "persuasion_influence",
        "Persuasion and influence",
        "leadership",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "creativity_constraints",
        "Creativity and innovation under constraints",
        "impact",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "learning_hard_skill_fast",
        "Learning a hard skill fast",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "customer_empathy",
        "User or customer empathy",
        "communication",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "research_curiosity",
        "A research-curiosity example",
        "curiosity",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "resilience_adversity",
        "Resilience through adversity",
        "resilience",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    # ── Values, motivation, fit (reflective) ──
    (
        "values_proof",
        "Your top 3 values, proven with a story",
        "ethics",
        "essay",
        None,
        250,
        "STAR",
        True,
        "core",
    ),
    (
        "motivation_drivers",
        "Your motivation drivers, ranked, with proof",
        "motivation",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
    (
        "why_this_field",
        "Why this field",
        "motivation",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
    (
        "why_this_program",
        "Why this program or school",
        "fit",
        "essay",
        None,
        300,
        "freeform",
        False,
        "school_specific",
    ),
    ("why_now", "Why now", "motivation", "essay", None, 200, "freeform", False, "core"),
    (
        "future_vision",
        "Your 5–10 year vision",
        "vision",
        "essay",
        None,
        300,
        "freeform",
        False,
        "core",
    ),
    # ── Curiosity / research depth ──
    (
        "intellectual_curiosity",
        "A topic you explored deeply on your own",
        "curiosity",
        "essay",
        None,
        250,
        "STAR",
        False,
        "core",
    ),
    (
        "research_process",
        "A research process: question → method → evidence → conclusion",
        "curiosity",
        "essay",
        None,
        300,
        "STAR",
        True,
        "core",
    ),
    (
        "hypothesis_tested",
        "A hypothesis you tested: predicted vs. actual",
        "curiosity",
        "essay",
        None,
        250,
        "STAR",
        True,
        "core",
    ),
    (
        "data_changed_decision",
        "Using data to change a decision",
        "impact",
        "essay",
        None,
        200,
        "STAR",
        True,
        "core",
    ),
    (
        "taught_yourself_difficult",
        "Teaching yourself something difficult",
        "learning",
        "essay",
        None,
        250,
        "STAR",
        False,
        "core",
    ),
    # ── Relationships, service, community ──
    (
        "mentorship_received",
        "Mentorship you received and applied",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "mentorship_given",
        "Mentorship you gave to develop someone",
        "leadership",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "community_impact",
        "A community-impact story: need → action → impact",
        "service",
        "essay",
        None,
        250,
        "STAR",
        True,
        "core",
    ),
    (
        "service_motivation",
        "Why you serve, and what you learned",
        "service",
        "essay",
        None,
        200,
        "freeform",
        False,
        "core",
    ),
    (
        "collaboration_breakdown",
        "A collaboration breakdown you fixed",
        "teamwork",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    # ── Resilience, accountability, ethics ──
    (
        "handled_rejection",
        "How you handled rejection",
        "resilience",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "principled_stand",
        "Taking a principled stand, with its cost",
        "ethics",
        "interview",
        180,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "managed_multiple_priorities",
        "Managing multiple priorities with a system",
        "impact",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "delivered_limited_resources",
        "Delivering results with limited resources",
        "impact",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "cultural_adaptation",
        "Adapting to a new environment",
        "resilience",
        "essay",
        None,
        250,
        "STAR",
        False,
        "core",
    ),
    (
        "belonging_inclusion",
        "Contributing to belonging and inclusion",
        "fit",
        "essay",
        None,
        250,
        "STAR",
        False,
        "core",
    ),
    (
        "empathy_support",
        "Supporting someone through difficulty",
        "communication",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "accountability_public_mistake",
        "Owning a mistake publicly",
        "ethics",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "perseverance_monotony",
        "Perseverance through a long grind",
        "resilience",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "integrity_pressure",
        "Integrity under pressure to cut corners",
        "ethics",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    # ── Self-knowledge, philosophy, short answers ──
    (
        "what_you_want_from_peers",
        "The team norms you value in peers",
        "teamwork",
        "short_answer",
        None,
        120,
        "freeform",
        False,
        "core",
    ),
    (
        "what_you_want_from_mentors",
        "The support you want from mentors and faculty",
        "fit",
        "short_answer",
        None,
        120,
        "freeform",
        False,
        "core",
    ),
    (
        "learn_from_failure_system",
        "The system you use to learn from failure",
        "learning",
        "short_answer",
        None,
        150,
        "freeform",
        False,
        "core",
    ),
    (
        "leadership_philosophy",
        "Your leadership philosophy, with an example",
        "leadership",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
    (
        "professional_identity",
        "How you describe yourself to a colleague",
        "identity",
        "short_answer",
        None,
        120,
        "freeform",
        False,
        "core",
    ),
    (
        "adaptability_new_tools",
        "Adapting to new tools or systems",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "handling_uncertainty",
        "What you do when you don't know",
        "learning",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "feedback_you_disagree",
        "Feedback you disagreed with, and how you responded",
        "communication",
        "interview",
        150,
        None,
        "STAR",
        False,
        "core",
    ),
    (
        "environment_preference",
        "Where you thrive, and why",
        "fit",
        "short_answer",
        None,
        150,
        "freeform",
        False,
        "core",
    ),
    (
        "program_contribution",
        "What you'll add to the cohort and community",
        "fit",
        "essay",
        None,
        250,
        "freeform",
        False,
        "school_specific",
    ),
    (
        "career_why",
        "Why this career is meaningful to you",
        "motivation",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
    (
        "ethical_ai_use",
        "How you decide the boundaries of AI and technology",
        "ethics",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
    (
        "global_perspective",
        "An experience that shaped your worldview",
        "identity",
        "essay",
        None,
        300,
        "STAR",
        False,
        "core",
    ),
    (
        "long_term_impact_goal",
        "Who you want to help, and how",
        "vision",
        "essay",
        None,
        250,
        "freeform",
        False,
        "core",
    ),
)


def seed_prompts() -> list[dict]:
    """Return the catalog as insert-ready dicts (sort_order = catalog position)."""
    rows: list[dict] = []
    for i, (key, title, intent, channel, time_s, word, fmt, evidence, reuse) in enumerate(_T):
        rows.append(
            {
                "prompt_key": key,
                "title": title,
                "intent_tag": intent,
                "target_channel": channel,
                "time_limit_seconds": time_s,
                "word_limit": word,
                "format_required": fmt,
                "evidence_required_flag": evidence,
                "allowed_attachments_flag": False,
                "language_option": "en",
                "confidentiality_scope": "private",
                "reuse_allowed_flag": reuse,
                "sort_order": i,
                "is_active": True,
            }
        )
    return rows


SEED_COUNT = len(_T)
