"""drop redundant ix_pipeline_configs_key index

Revision ID: 0ebebb7c82a4
Revises: cce471db5933
Create Date: 2026-04-13 20:42:40.004800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebebb7c82a4'
down_revision: Union[str, None] = '7fa321c6e551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_configs_key'), table_name='pipeline_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipeline_configs_key'), 'pipeline_configs', ['key'], unique=False)
    # ### end Alembic commands ###
