"""add student research

Revision ID: 1df92271d348
Revises: cce4d85f1147
Create Date: 2026-04-08 15:51:09.308335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df92271d348'
down_revision: Union[str, None] = 'cce4d85f1147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('institution_lab', sa.String(length=255), nullable=True),
    sa.Column('field_discipline', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('advisor_name', sa.String(length=255), nullable=True),
    sa.Column('methods_tools', sa.Text(), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('outputs', sa.String(length=50), nullable=True),
    sa.Column('publication_link', sa.String(length=1000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_research_student_id'), 'student_research', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_research_student_id'), table_name='student_research')
    op.drop_table('student_research')
    # ### end Alembic commands ###
