"""enrich_institution_and_program_models

Revision ID: 344185d8499f
Revises: f4cfc12d17ac
Create Date: 2026-04-06 18:13:15.908404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344185d8499f'
down_revision: Union[str, None] = 'f4cfc12d17ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_institution_last_message'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_student_last_message'), table_name='conversations')
    op.create_foreign_key(None, 'crawl_frontier', 'knowledge_documents', ['discovered_from_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_historical_outcomes_program_outcome'), table_name='historical_outcomes')
    op.add_column('institutions', sa.Column('campus_description', sa.Text(), nullable=True))
    op.add_column('institutions', sa.Column('campus_setting', sa.String(length=30), nullable=True))
    op.add_column('institutions', sa.Column('student_body_size', sa.Integer(), nullable=True))
    op.add_column('institutions', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('institutions', sa.Column('media_gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('institutions', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_messages_conversation_read_sender'), table_name='messages')
    op.add_column('programs', sa.Column('delivery_format', sa.String(length=30), nullable=True))
    op.add_column('programs', sa.Column('campus_setting', sa.String(length=30), nullable=True))
    op.add_column('programs', sa.Column('application_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('programs', sa.Column('who_its_for', sa.Text(), nullable=True))
    op.add_column('programs', sa.Column('tracks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('programs', sa.Column('outcomes_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('programs', sa.Column('intake_rounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('programs', sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('programs', 'page_header_image_url')
    op.drop_column('programs', 'current_preferences_text')
    op.drop_index(op.f('ix_target_segments_program_active'), table_name='target_segments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_target_segments_program_active'), 'target_segments', ['program_id', 'is_active'], unique=False)
    op.add_column('programs', sa.Column('current_preferences_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('programs', sa.Column('page_header_image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('programs', 'media_urls')
    op.drop_column('programs', 'intake_rounds')
    op.drop_column('programs', 'outcomes_data')
    op.drop_column('programs', 'tracks')
    op.drop_column('programs', 'who_its_for')
    op.drop_column('programs', 'application_requirements')
    op.drop_column('programs', 'campus_setting')
    op.drop_column('programs', 'delivery_format')
    op.create_index(op.f('ix_messages_conversation_read_sender'), 'messages', ['conversation_id', 'read_at', 'sender_id'], unique=False)
    op.drop_column('institutions', 'social_links')
    op.drop_column('institutions', 'media_gallery')
    op.drop_column('institutions', 'contact_email')
    op.drop_column('institutions', 'student_body_size')
    op.drop_column('institutions', 'campus_setting')
    op.drop_column('institutions', 'campus_description')
    op.create_index(op.f('ix_historical_outcomes_program_outcome'), 'historical_outcomes', ['program_id', 'outcome'], unique=False)
    op.drop_constraint(None, 'crawl_frontier', type_='foreignkey')
    op.create_index(op.f('ix_conversations_student_last_message'), 'conversations', ['student_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_institution_last_message'), 'conversations', ['institution_id', 'last_message_at'], unique=False)
    # ### end Alembic commands ###
