"""add student_program_reviews

Revision ID: 43c8297c43fa
Revises: 5254d672d4da
Create Date: 2026-04-09 17:33:12.467723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c8297c43fa'
down_revision: Union[str, None] = '5254d672d4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_program_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('rating_teaching', sa.Integer(), nullable=True),
    sa.Column('rating_workload', sa.Integer(), nullable=True),
    sa.Column('rating_career_support', sa.Integer(), nullable=True),
    sa.Column('rating_roi', sa.Integer(), nullable=True),
    sa.Column('rating_overall', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('who_thrives_here', sa.Text(), nullable=True),
    sa.Column('reviewer_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'program_id')
    )
    op.create_index(op.f('ix_student_program_reviews_program_id'), 'student_program_reviews', ['program_id'], unique=False)
    op.create_index(op.f('ix_student_program_reviews_student_id'), 'student_program_reviews', ['student_id'], unique=False)
    op.create_unique_constraint('uq_ai_packet_app', 'ai_packet_summaries', ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ai_packet_app', 'ai_packet_summaries', type_='unique')
    op.drop_index(op.f('ix_student_program_reviews_student_id'), table_name='student_program_reviews')
    op.drop_index(op.f('ix_student_program_reviews_program_id'), table_name='student_program_reviews')
    op.drop_table('student_program_reviews')
    # ### end Alembic commands ###
