"""add student languages

Revision ID: 481c4c6a2b99
Revises: 1df92271d348
Create Date: 2026-04-08 17:03:04.482021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481c4c6a2b99'
down_revision: Union[str, None] = '1df92271d348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), nullable=False),
    sa.Column('certification_type', sa.String(length=100), nullable=True),
    sa.Column('certification_score', sa.String(length=50), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_languages_student_id'), 'student_languages', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_languages_student_id'), table_name='student_languages')
    op.drop_table('student_languages')
    # ### end Alembic commands ###
