"""add employer_feedback

Revision ID: 51c72506f2d4
Revises: 43c8297c43fa
Create Date: 2026-04-09 17:37:41.844932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c72506f2d4'
down_revision: Union[str, None] = '43c8297c43fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('rating_technical', sa.Integer(), nullable=True),
    sa.Column('rating_practical', sa.Integer(), nullable=True),
    sa.Column('rating_communication', sa.Integer(), nullable=True),
    sa.Column('rating_overall', sa.Integer(), nullable=True),
    sa.Column('job_readiness_sentiment', sa.String(length=20), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('hiring_pattern', sa.String(length=255), nullable=True),
    sa.Column('feedback_year', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_feedback_program_id'), 'employer_feedback', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employer_feedback_program_id'), table_name='employer_feedback')
    op.drop_table('employer_feedback')
    # ### end Alembic commands ###
