"""add student courses scheduling visa consent tables and fix nullability

Revision ID: 7ae1dec79e29
Revises: f6g7h8i9j0k1
Create Date: 2026-04-09 06:14:41.010596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae1dec79e29'
down_revision: Union[str, None] = 'f6g7h8i9j0k1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data_consent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('consent_matching', sa.Boolean(), nullable=False),
    sa.Column('consent_outreach', sa.Boolean(), nullable=False),
    sa.Column('consent_research', sa.Boolean(), nullable=False),
    sa.Column('data_retention_preference', sa.String(length=30), nullable=True),
    sa.Column('deletion_requested', sa.Boolean(), nullable=False),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_scheduling',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('general_availability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_interview_format', sa.String(length=30), nullable=True),
    sa.Column('campus_visit_interest', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_visa_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('current_immigration_status', sa.String(length=50), nullable=True),
    sa.Column('visa_required', sa.Boolean(), nullable=False),
    sa.Column('target_study_country', sa.String(length=100), nullable=True),
    sa.Column('passport_expiration_date', sa.Date(), nullable=True),
    sa.Column('sponsorship_source', sa.String(length=50), nullable=True),
    sa.Column('financial_proof_available', sa.Boolean(), nullable=False),
    sa.Column('financial_proof_amount_band', sa.String(length=50), nullable=True),
    sa.Column('post_study_work_interest', sa.Boolean(), nullable=False),
    sa.Column('prior_visa_refusals', sa.Boolean(), nullable=False),
    sa.Column('travel_constraints', sa.Text(), nullable=True),
    sa.Column('work_authorization_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('student_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('academic_record_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('subject_area', sa.String(length=100), nullable=True),
    sa.Column('course_level', sa.String(length=30), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('credits', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_record_id'], ['academic_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_courses_academic_record_id'), 'student_courses', ['academic_record_id'], unique=False)
    op.add_column('academic_records', sa.Column('transcript_language', sa.String(length=50), nullable=True))
    op.add_column('academic_records', sa.Column('credential_evaluation_status', sa.String(length=30), nullable=True))
    op.add_column('academic_records', sa.Column('credential_evaluation_report_url', sa.String(length=1000), nullable=True))
    op.add_column('academic_records', sa.Column('rigor_indicator_count', sa.Integer(), nullable=True))
    op.alter_column('institution_datasets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('institution_datasets', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('institution_posts', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('institution_posts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('institution_posts', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('institution_posts', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('institution_posts', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('institution_posts', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('institution_posts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('institution_posts', 'pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('institution_datasets', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('institution_datasets', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('academic_records', 'rigor_indicator_count')
    op.drop_column('academic_records', 'credential_evaluation_report_url')
    op.drop_column('academic_records', 'credential_evaluation_status')
    op.drop_column('academic_records', 'transcript_language')
    op.drop_index(op.f('ix_student_courses_academic_record_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_table('student_visa_info')
    op.drop_table('student_scheduling')
    op.drop_table('student_data_consent')
    # ### end Alembic commands ###
