"""add conversation_sessions table

Revision ID: 7fa321c6e551
Revises: 89920187e2c6
Create Date: 2026-04-11 11:09:57.350767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa321c6e551'
down_revision: Union[str, None] = '89920187e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('active_domain', sa.String(length=50), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('requirements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_assistant_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_conversation_sessions_student_id'), 'conversation_sessions', ['student_id'], unique=False)
    op.alter_column('conversations', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_conversation_sessions_student_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
