"""add student work experiences

Revision ID: 82b559aa66b1
Revises: 481c4c6a2b99
Create Date: 2026-04-08 17:32:55.962382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b559aa66b1'
down_revision: Union[str, None] = '481c4c6a2b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('experience_type', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('compensation_type', sa.String(length=30), nullable=True),
    sa.Column('key_achievements', sa.Text(), nullable=True),
    sa.Column('supervisor_name', sa.String(length=255), nullable=True),
    sa.Column('organization_country', sa.String(length=100), nullable=True),
    sa.Column('organization_city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_work_experiences_student_id'), 'student_work_experiences', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_work_experiences_student_id'), table_name='student_work_experiences')
    op.drop_table('student_work_experiences')
    # ### end Alembic commands ###
