"""add institution detail fields

Revision ID: 89920187e2c6
Revises: 0b9d40c2c23c
Create Date: 2026-04-09 17:42:52.384587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89920187e2c6'
down_revision: Union[str, None] = '0b9d40c2c23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('support_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('institutions', sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('institutions', sa.Column('international_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('institutions', sa.Column('school_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'school_outcomes')
    op.drop_column('institutions', 'international_info')
    op.drop_column('institutions', 'policies')
    op.drop_column('institutions', 'support_services')
    # ### end Alembic commands ###
