"""make conversation institution_id nullable

Revision ID: d2a90164a076
Revises: 89920187e2c6
Create Date: 2026-04-11 09:25:55.045865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a90164a076'
down_revision: Union[str, None] = '89920187e2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'institution_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'institution_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
