"""add cost_data to programs

Revision ID: f3da9591d4a9
Revises: d6cc531e526f
Create Date: 2026-04-09 17:20:22.105578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3da9591d4a9'
down_revision: Union[str, None] = 'd6cc531e526f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('cost_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'cost_data')
    # ### end Alembic commands ###
