"""add pipeline tables

Revision ID: f4cfc12d17ac
Revises: e5f1a2b3c904
Create Date: 2026-04-02 19:28:04.574409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4cfc12d17ac'
down_revision: Union[str, None] = 'e5f1a2b3c904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_pipeline_configs_key', 'pipeline_configs', ['key'], unique=False)
    op.create_table('pipeline_stage_snapshots',
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed_total', sa.Integer(), nullable=False),
    sa.Column('items_processed_hour', sa.Integer(), nullable=False),
    sa.Column('hour_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worker_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_hostname', sa.String(length=255), nullable=True),
    sa.Column('budget_spent_this_hour', sa.Float(), nullable=False),
    sa.Column('budget_per_hour', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_stage_snapshots')
    op.drop_index('ix_pipeline_configs_key', table_name='pipeline_configs')
    op.drop_table('pipeline_configs')
    # ### end Alembic commands ###
